# Generated by Django 6.0.2 on 2026-02-28 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="zinesubmission",
            name="send_digital",
            field=models.BooleanField(
                default=False, help_text="Send digital copy of the zine"
            ),
        ),
        migrations.AddField(
            model_name="zinesubmission",
            name="send_print",
            field=models.BooleanField(
                default=False, help_text="Send print copy of the zine"
            ),
        ),
    ]
