# Generated by Django 6.0.2 on 2026-03-01 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_zinesubmission_send_digital_and_more"),
        ("agents", "0005_remove_legacy_external_fields"),
        (
            "repositories",
            "0009_repository_is_active_repository_submission_allowed_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="agent",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="repository",
        ),
        migrations.CreateModel(
            name="ProfileAgentClaim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="requested",
                        help_text="Approval status of this claim",
                        max_length=20,
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Notes about this claim (reason, approval notes, etc.)",
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_claims",
                        to="agents.agent",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_claims",
                        to="accounts.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Profile Agent Claim",
                "verbose_name_plural": "Profile Agent Claims",
                "db_table": "profile_agent_claims",
                "ordering": ["-created_at"],
                "unique_together": {("profile", "agent")},
            },
        ),
        migrations.AddField(
            model_name="profile",
            name="agents",
            field=models.ManyToManyField(
                help_text="Agents this profile has claims on",
                related_name="profiles",
                through="accounts.ProfileAgentClaim",
                to="agents.agent",
            ),
        ),
        migrations.CreateModel(
            name="ProfileRepositoryClaim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="requested",
                        help_text="Approval status of this claim",
                        max_length=20,
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Notes about this claim (reason, approval notes, etc.)",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repository_claims",
                        to="accounts.profile",
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_claims",
                        to="repositories.repository",
                    ),
                ),
            ],
            options={
                "verbose_name": "Profile Repository Claim",
                "verbose_name_plural": "Profile Repository Claims",
                "db_table": "profile_repository_claims",
                "ordering": ["-created_at"],
                "unique_together": {("profile", "repository")},
            },
        ),
        migrations.AddField(
            model_name="profile",
            name="repositories",
            field=models.ManyToManyField(
                help_text="Repositories this profile has claims on",
                related_name="profiles",
                through="accounts.ProfileRepositoryClaim",
                to="repositories.repository",
            ),
        ),
    ]
