# Generated by Django 6.0.2 on 2026-02-23 19:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentKind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('label', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Agent Kind',
                'verbose_name_plural': 'Agent Kinds',
                'db_table': 'agent_kinds',
                'ordering': ['label'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AgentRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('label', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Agent Role',
                'verbose_name_plural': 'Agent Roles',
                'db_table': 'agent_roles',
                'ordering': ['label'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent_id', models.CharField(help_text="Stable external identifier (e.g. 'agent_doris').", max_length=64, unique=True)),
                ('kind', models.CharField(help_text="Agent type: 'person', 'collective', 'organization', 'other', 'unknown'.", max_length=32)),
                ('display_name', models.CharField(max_length=255)),
                ('legal_name', models.CharField(blank=True, max_length=255, null=True)),
                ('aliases', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list)),
                ('roles', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, default=list)),
                ('website', models.URLField(blank=True)),
                ('orcid', models.URLField(blank=True)),
                ('wikidata_id', models.CharField(blank=True, max_length=32)),
                ('public', models.BooleanField(default=True)),
                ('notes', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list)),
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agents',
                'db_table': 'agents',
                'indexes': [models.Index(fields=['agent_id'], name='agents_agent_i_cdfbf2_idx'), models.Index(fields=['display_name'], name='agents_display_a9e33f_idx')],
            },
        ),
    ]
