# Generated by Django 6.0.2 on 2026-02-24 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agent",
            name="roles",
        ),
        migrations.AlterField(
            model_name="agent",
            name="kind",
            field=models.ForeignKey(
                help_text="Agent type: 'person', 'collective', 'organization', 'other', 'unknown'.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="agents",
                to="agents.agentkind",
            ),
        ),
    ]
