# Generated by Django 6.0.2 on 2026-02-24 17:46

import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_remove_agent_roles_alter_agent_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='agent_id',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, help_text="Auto-generated slug (e.g. 'a-doris').", max_length=64, populate_from='slug_source', unique=True),
        ),
    ]
