# Generated by Django 6.0.2 on 2026-02-24 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_alter_agent_agent_id'),
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Geographic location from GeoNames hierarchy.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='geography.geoplace'),
        ),
    ]
