# Generated by Django 6.0.2 on 2026-02-24 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_agent_location'),
        ('core', '0002_migrate_legacy_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='orcid',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='website',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='wikidata_id',
        ),
    ]
