# Generated by Django 6.0.2 on 2026-02-23 19:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('label', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
                'db_table': 'genres',
                'ordering': ['label'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RightsStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('label', models.CharField(max_length=255)),
                ('uri', models.URLField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Rights Statement',
                'verbose_name_plural': 'Rights Statements',
                'db_table': 'rights_statements',
                'ordering': ['label'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('label', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'db_table': 'subjects',
                'ordering': ['label'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Zine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('zine_id', models.CharField(help_text="Stable external identifier (e.g. 'zine_mutate_3_1st').", max_length=64, unique=True)),
                ('title', models.CharField(max_length=512)),
                ('series_title', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list)),
                ('issue_designation', models.CharField(blank=True, max_length=255, null=True)),
                ('edition_statement', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list)),
                ('alternative_title', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list)),
                ('creator', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255))),
                ('contributor', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list)),
                ('subject', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255))),
                ('genre', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255))),
                ('abstract', models.TextField(blank=True)),
                ('table_of_contents', models.TextField(blank=True)),
                ('public_notes', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list)),
                ('publisher', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list)),
                ('date', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64))),
                ('physical_dimensions', models.CharField(blank=True, max_length=255)),
                ('number_of_pages', models.CharField(blank=True, max_length=64)),
                ('format', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list)),
                ('binding_features', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list)),
                ('language', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=16))),
                ('place_of_publication', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list)),
                ('coverage', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list)),
                ('source', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list)),
                ('relation', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list)),
                ('rights', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255))),
                ('identifier', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list)),
                ('genres', models.ManyToManyField(blank=True, related_name='zines', to='catalog.genre')),
                ('subjects', models.ManyToManyField(blank=True, related_name='zines', to='catalog.subject')),
            ],
            options={
                'verbose_name': 'Zine',
                'verbose_name_plural': 'Zines',
                'db_table': 'zines',
                'indexes': [models.Index(fields=['zine_id'], name='zines_zine_id_70993d_idx'), models.Index(fields=['title'], name='zines_title_d8cd9a_idx')],
            },
        ),
    ]
