# Generated by Django 6.0.2 on 2026-02-24 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0001_initial"),
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=64, unique=True)),
                ("label", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Language",
                "verbose_name_plural": "Languages",
                "db_table": "languages",
                "ordering": ["label"],
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="zine",
            name="contributor",
        ),
        migrations.RemoveField(
            model_name="zine",
            name="creator",
        ),
        migrations.RemoveField(
            model_name="zine",
            name="date",
        ),
        migrations.RemoveField(
            model_name="zine",
            name="genre",
        ),
        migrations.RemoveField(
            model_name="zine",
            name="language",
        ),
        migrations.RemoveField(
            model_name="zine",
            name="publisher",
        ),
        migrations.RemoveField(
            model_name="zine",
            name="rights",
        ),
        migrations.RemoveField(
            model_name="zine",
            name="subject",
        ),
        migrations.AddField(
            model_name="zine",
            name="publish_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="zine",
            name="rights_statement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="zines",
                to="catalog.rightsstatement",
            ),
        ),
        migrations.AlterField(
            model_name="zine",
            name="binding_features",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="zine",
            name="edition_statement",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="zine",
            name="format",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="zine",
            name="genres",
            field=models.ManyToManyField(related_name="zines", to="catalog.genre"),
        ),
        migrations.AlterField(
            model_name="zine",
            name="place_of_publication",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="zine",
            name="series_title",
            field=models.CharField(blank=True, default="", max_length=512),
        ),
        migrations.AlterField(
            model_name="zine",
            name="subjects",
            field=models.ManyToManyField(related_name="zines", to="catalog.subject"),
        ),
        migrations.AddField(
            model_name="zine",
            name="languages",
            field=models.ManyToManyField(
                blank=True, related_name="zines", to="catalog.language"
            ),
        ),
        migrations.CreateModel(
            name="ZineContributor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="agents.agent"
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="agents.agentrole",
                    ),
                ),
                (
                    "zine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="catalog.zine"
                    ),
                ),
            ],
            options={
                "verbose_name": "Zine Contributor",
                "verbose_name_plural": "Zine Contributors",
                "db_table": "zine_contributors",
                "ordering": ["order"],
                "unique_together": {("zine", "agent", "role")},
            },
        ),
        migrations.AddField(
            model_name="zine",
            name="contributors",
            field=models.ManyToManyField(
                blank=True,
                related_name="zines_contributed",
                through="catalog.ZineContributor",
                to="agents.agent",
            ),
        ),
        migrations.CreateModel(
            name="ZineCreator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="agents.agent"
                    ),
                ),
                (
                    "zine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="catalog.zine"
                    ),
                ),
            ],
            options={
                "verbose_name": "Zine Creator",
                "verbose_name_plural": "Zine Creators",
                "db_table": "zine_creators",
                "ordering": ["order"],
                "unique_together": {("zine", "agent", "order")},
            },
        ),
        migrations.AddField(
            model_name="zine",
            name="creators",
            field=models.ManyToManyField(
                blank=True,
                related_name="zines_created",
                through="catalog.ZineCreator",
                to="agents.agent",
            ),
        ),
        migrations.CreateModel(
            name="ZinePublisher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="agents.agent"
                    ),
                ),
                (
                    "zine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="catalog.zine"
                    ),
                ),
            ],
            options={
                "verbose_name": "Zine Publisher",
                "verbose_name_plural": "Zine Publishers",
                "db_table": "zine_publishers",
                "ordering": ["order"],
                "unique_together": {("zine", "agent", "order")},
            },
        ),
        migrations.AddField(
            model_name="zine",
            name="publishers",
            field=models.ManyToManyField(
                blank=True,
                related_name="zines_published",
                through="catalog.ZinePublisher",
                to="agents.agent",
            ),
        ),
    ]
