# Generated by Django 6.0.2 on 2026-02-24 17:46

import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_language_remove_zine_contributor_remove_zine_creator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zine',
            name='zine_id',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, help_text="Auto-generated slug (e.g. 'z-mutate-3').", max_length=64, populate_from='slug_source', unique=True),
        ),
    ]
