# Generated by Django 6.0.2 on 2026-02-24 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_zine_zine_id'),
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zine',
            name='place_of_publication',
            field=models.ForeignKey(blank=True, help_text='Place of publication from GeoNames hierarchy.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zines_published_here', to='geography.geoplace'),
        ),
    ]
