[project]
name = "zinecore-backend"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "django",
    "djangorestframework",
    "django-filter",
    "drf-spectacular",
    "psycopg[binary]",
    "gunicorn",
    "django-unfold",
    "requests",
    "werkzeug>=3.1.6",
    "django-extensions>=4.1",
]

[dependency-groups]
dev = [
    "textual",
]

[tool.hatch.build.targets.wheel]
packages = [
    "core",
    "catalog",
    "agents",
    "repositories",
    "geography",
    "holdings",
    "zinecore",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
