# Generated by Django 6.0.2 on 2026-02-23 19:23

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('repositories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('label', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Access Status',
                'verbose_name_plural': 'Access Statuses',
                'db_table': 'holding_access_statuses',
                'ordering': ['label'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DistroStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('label', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Distribution Status',
                'verbose_name_plural': 'Distribution Statuses',
                'db_table': 'holding_distro_statuses',
                'ordering': ['label'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('holding_id', models.CharField(help_text="Stable external identifier (e.g. 'holding_qzap_heavy_mayo_1').", max_length=64, unique=True)),
                ('call_number', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('access_status', models.CharField(blank=True, max_length=64)),
                ('condition', models.CharField(blank=True, max_length=64)),
                ('copy_count', models.PositiveIntegerField(blank=True, null=True)),
                ('barcode', models.CharField(blank=True, max_length=64)),
                ('digital_available', models.BooleanField(default=False)),
                ('digital_url', models.URLField(blank=True)),
                ('distro_status', models.CharField(blank=True, max_length=64)),
                ('notes', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='repositories.repository')),
                ('zine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='catalog.zine')),
            ],
            options={
                'verbose_name': 'Holding',
                'verbose_name_plural': 'Holdings',
                'db_table': 'holdings',
                'indexes': [models.Index(fields=['holding_id'], name='holdings_holding_1bd635_idx'), models.Index(fields=['repository', 'zine'], name='holdings_reposit_8f2521_idx')],
            },
        ),
    ]
