# Generated by Django 6.0.2 on 2026-02-24 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("holdings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="holding",
            name="access_status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="holdings",
                to="holdings.accessstatus",
            ),
        ),
        migrations.AlterField(
            model_name="holding",
            name="distro_status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="holdings",
                to="holdings.distrostatus",
            ),
        ),
    ]
