# Generated by Django 6.0.2 on 2026-02-24 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holdings', '0002_alter_holding_access_status_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='holding',
            name='holdings_holding_1bd635_idx',
        ),
        migrations.RemoveField(
            model_name='holding',
            name='holding_id',
        ),
    ]
