# Generated by Django 6.0.2 on 2026-02-24 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geoname_id', models.PositiveIntegerField(help_text='GeoNames database ID.', unique=True)),
                ('name', models.CharField(max_length=200)),
                ('ascii_name', models.CharField(blank=True, max_length=200)),
                ('feature_class', models.CharField(help_text="GeoNames feature class: 'A' admin, 'P' populated place.", max_length=1)),
                ('feature_code', models.CharField(help_text='GeoNames feature code: PCLI, ADM1, PPL, PPLA, etc.', max_length=10)),
                ('country_code', models.CharField(db_index=True, help_text='ISO 3166-1 alpha-2 country code.', max_length=2)),
                ('admin1_code', models.CharField(blank=True, help_text='First-order admin division code.', max_length=20)),
                ('continent_code', models.CharField(blank=True, help_text='Continent code (AF, AS, EU, NA, OC, SA, AN).', max_length=2)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('population', models.BigIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='geography.geoplace')),
            ],
            options={
                'verbose_name': 'Geographic Place',
                'verbose_name_plural': 'Geographic Places',
                'db_table': 'geo_places',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['geoname_id'], name='geo_places_geoname_24c4af_idx'), models.Index(fields=['country_code', 'admin1_code'], name='geo_places_country_d24822_idx'), models.Index(fields=['feature_code'], name='geo_places_feature_72d00c_idx'), models.Index(fields=['name'], name='geo_places_name_836469_idx')],
            },
        ),
    ]
