# Generated by Django 6.0.2 on 2026-02-23 19:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RepoKind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('label', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Repository Kind',
                'verbose_name_plural': 'Repository Kinds',
                'db_table': 'repo_kinds',
                'ordering': ['label'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('repo_id', models.CharField(help_text="Stable external identifier (e.g. 'repo_qzap').", max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('kind', models.CharField(help_text="Repository type: 'library', 'archive', 'zine-library', 'distro', etc.", max_length=64)),
                ('homepage', models.URLField(blank=True)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('region', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(max_length=2)),
                ('marc_org_code', models.CharField(blank=True, max_length=16)),
                ('isil', models.CharField(blank=True, max_length=32)),
                ('ror_id', models.URLField(blank=True)),
                ('access_policy', models.TextField(blank=True)),
                ('hours', models.TextField(blank=True)),
                ('notes', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list)),
            ],
            options={
                'verbose_name': 'Repository',
                'verbose_name_plural': 'Repositories',
                'db_table': 'repositories',
                'indexes': [models.Index(fields=['repo_id'], name='repositorie_repo_id_a86946_idx'), models.Index(fields=['name'], name='repositorie_name_174419_idx')],
            },
        ),
    ]
