# Generated by Django 6.0.2 on 2026-02-24 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repositories", "0002_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="repository",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="repositories",
                to="repositories.country",
            ),
        ),
        migrations.AlterField(
            model_name="repository",
            name="kind",
            field=models.ForeignKey(
                help_text="Repository type: 'library', 'archive', 'zine-library', 'distro', etc.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="repositories",
                to="repositories.repokind",
            ),
        ),
    ]
