# Generated by Django 6.0.2 on 2026-02-24 17:46

import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0003_alter_repository_country_alter_repository_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='repo_id',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, help_text="Auto-generated slug (e.g. 'r-qzap').", max_length=64, populate_from='slug_source', unique=True),
        ),
    ]
