# Generated by Django 6.0.2 on 2026-02-24 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0001_initial'),
        ('repositories', '0004_alter_repository_repo_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repository',
            name='country',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='city',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='region',
        ),
        migrations.AddField(
            model_name='repository',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Geographic location from GeoNames hierarchy.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='repositories', to='geography.geoplace'),
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
