# Generated by Django 6.0.2 on 2026-02-24 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0005_remove_repository_country_remove_repository_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='address',
            field=models.TextField(blank=True),
        ),
    ]
