# Generated by Django 6.0.2 on 2026-02-24 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0006_repository_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='isil',
            field=models.CharField(blank=True, help_text="International Standard Identifier for Libraries and Related Organizations / ISO 15511 (<a href='https://www.loc.gov/marc/organizations/org-search.php' target='_blank'>LOC Lookup</a>)", max_length=32, verbose_name='ISIL Code'),
        ),
        migrations.AlterField(
            model_name='repository',
            name='marc_org_code',
            field=models.CharField(blank=True, help_text="<a href='https://www.loc.gov/marc/organizations/org-search.php' target='_blank'>Library of Congress MARC Record ID</a>)", max_length=16, verbose_name='MARC Organization Code'),
        ),
        migrations.AlterField(
            model_name='repository',
            name='ror_id',
            field=models.URLField(blank=True, help_text="<a href='https://ror.org/' target='_blank'>Research Organization Registry Codes</a>", verbose_name='ROR Code'),
        ),
    ]
