# Generated by Django 6.0.2 on 2026-02-24 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0007_external_models'),
        ('core', '0002_migrate_legacy_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repository',
            name='homepage',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='isil',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='marc_org_code',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='ror_id',
        ),
    ]
