# Generated by Django 6.0.2 on 2026-02-28 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repositories", "0008_remove_legacy_external_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="repository",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="repository",
            name="submission_allowed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="repository",
            name="submission_notes",
            field=models.TextField(blank=True),
        ),
    ]
