# Generated by Django 6.0.2 on 2026-02-24 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0004_agent_location'),
        ('geography', '0001_initial'),
        ('repositories', '0007_external_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalUriType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('label', models.CharField(max_length=255)),
                ('base_uri', models.URLField(blank=True, default='', help_text='Base URL prefix for the platform, if applicable.')),
                ('category', models.CharField(choices=[('web', 'Web'), ('social', 'Social'), ('tech', 'Tech')], default='web', max_length=16)),
                ('icon', models.CharField(blank=True, default='', help_text='Material icon name for UI rendering.', max_length=64)),
            ],
            options={
                'verbose_name': 'External URI Type',
                'verbose_name_plural': 'External URI Types',
                'db_table': 'external_uri_types',
                'ordering': ['label'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExternalIdSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('label', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('lookup_uri', models.URLField(blank=True, default='', help_text='URL template/base for looking up a specific identifier value.')),
                ('info_uri', models.URLField(blank=True, default='', help_text='Link to documentation or spec for this identifier system.')),
                ('owner_uri', models.URLField(blank=True, default='', help_text='Link to the responsible authority that manages the standard.')),
                ('applicable_to', models.CharField(choices=[('agent', 'Agent'), ('repository', 'Repository'), ('both', 'Both')], default='both', max_length=16)),
                ('authority_scope', models.ForeignKey(blank=True, help_text='Geographic scope of the authority (null = international/global).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='geography.geoplace')),
            ],
            options={
                'verbose_name': 'External ID System',
                'verbose_name_plural': 'External ID Systems',
                'db_table': 'external_id_systems',
                'ordering': ['label'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExternalIdentifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(max_length=255)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='external_ids', to='agents.agent')),
                ('repository', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='external_ids', to='repositories.repository')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='identifiers', to='core.externalidsystem')),
            ],
            options={
                'verbose_name': 'External Identifier',
                'verbose_name_plural': 'External Identifiers',
                'db_table': 'external_identifiers',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('agent__isnull', False), ('repository__isnull', True)), models.Q(('agent__isnull', True), ('repository__isnull', False)), _connector='OR'), name='ext_id_exactly_one_owner'), models.UniqueConstraint(condition=models.Q(('agent__isnull', False)), fields=('system', 'agent'), name='ext_id_unique_system_agent'), models.UniqueConstraint(condition=models.Q(('repository__isnull', False)), fields=('system', 'repository'), name='ext_id_unique_system_repository')],
            },
        ),
        migrations.CreateModel(
            name='ExternalUri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uri', models.URLField()),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='external_uris', to='agents.agent')),
                ('repository', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='external_uris', to='repositories.repository')),
                ('uri_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uris', to='core.externaluritype')),
            ],
            options={
                'verbose_name': 'External URI',
                'verbose_name_plural': 'External URIs',
                'db_table': 'external_uris',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('agent__isnull', False), ('repository__isnull', True)), models.Q(('agent__isnull', True), ('repository__isnull', False)), _connector='OR'), name='ext_uri_exactly_one_owner')],
            },
        ),
    ]
